spring:
  datasource:
    username: jdbc
    password: JDBCjdbc000
    url: jdbc:mysql://rm-4xo63l909kdrexz8kio.mysql.germany.rds.aliyuncs.com:3306/jdbc_test?rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat,wall,log4j
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
        allow: 127.0.0.1
mybatis:
  type-aliases-package: com.ayy.bean
  mapper-locations: classpath:mybatis/mapper/*.xml