spring:
  datasource:
    username: jdbc
    password: JDBCjdbc000
    url: jdbc:mysql://rm-4xo63l909kdrexz8kio.mysql.germany.rds.aliyuncs.com:3306/jdbc_test?rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver