// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Animal.proto

package com.ayy.protobuf;

public final class MyDataInfo {
  private MyDataInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MyMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ayy.protobuf.MyMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .com.ayy.protobuf.MyMessage.AnimalType animal_type = 1;</code>
     * @return Whether the animalType field is set.
     */
    boolean hasAnimalType();
    /**
     * <code>required .com.ayy.protobuf.MyMessage.AnimalType animal_type = 1;</code>
     * @return The animalType.
     */
    MyMessage.AnimalType getAnimalType();

    /**
     * <code>.com.ayy.protobuf.Cat cat = 2;</code>
     * @return Whether the cat field is set.
     */
    boolean hasCat();
    /**
     * <code>.com.ayy.protobuf.Cat cat = 2;</code>
     * @return The cat.
     */
    Cat getCat();
    /**
     * <code>.com.ayy.protobuf.Cat cat = 2;</code>
     */
    CatOrBuilder getCatOrBuilder();

    /**
     * <code>.com.ayy.protobuf.Dog dog = 3;</code>
     * @return Whether the dog field is set.
     */
    boolean hasDog();
    /**
     * <code>.com.ayy.protobuf.Dog dog = 3;</code>
     * @return The dog.
     */
    Dog getDog();
    /**
     * <code>.com.ayy.protobuf.Dog dog = 3;</code>
     */
    DogOrBuilder getDogOrBuilder();

    public MyMessage.OneOfAnimalCase getOneOfAnimalCase();
  }
  /**
   * Protobuf type {@code com.ayy.protobuf.MyMessage}
   */
  public static final class MyMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ayy.protobuf.MyMessage)
      MyMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MyMessage.newBuilder() to construct.
    private MyMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MyMessage() {
      animalType_ = 1;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new MyMessage();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MyMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              AnimalType value = AnimalType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                animalType_ = rawValue;
              }
              break;
            }
            case 18: {
              Cat.Builder subBuilder = null;
              if (oneOfAnimalCase_ == 2) {
                subBuilder = ((Cat) oneOfAnimal_).toBuilder();
              }
              oneOfAnimal_ =
                  input.readMessage(Cat.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((Cat) oneOfAnimal_);
                oneOfAnimal_ = subBuilder.buildPartial();
              }
              oneOfAnimalCase_ = 2;
              break;
            }
            case 26: {
              Dog.Builder subBuilder = null;
              if (oneOfAnimalCase_ == 3) {
                subBuilder = ((Dog) oneOfAnimal_).toBuilder();
              }
              oneOfAnimal_ =
                  input.readMessage(Dog.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((Dog) oneOfAnimal_);
                oneOfAnimal_ = subBuilder.buildPartial();
              }
              oneOfAnimalCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MyDataInfo.internal_static_com_ayy_protobuf_MyMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MyDataInfo.internal_static_com_ayy_protobuf_MyMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MyMessage.class, Builder.class);
    }

    /**
     * Protobuf enum {@code com.ayy.protobuf.MyMessage.AnimalType}
     */
    public enum AnimalType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CAT = 1;</code>
       */
      CAT(1),
      /**
       * <code>DOG = 2;</code>
       */
      DOG(2),
      ;

      /**
       * <code>CAT = 1;</code>
       */
      public static final int CAT_VALUE = 1;
      /**
       * <code>DOG = 2;</code>
       */
      public static final int DOG_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static AnimalType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static AnimalType forNumber(int value) {
        switch (value) {
          case 1: return CAT;
          case 2: return DOG;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<AnimalType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          AnimalType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<AnimalType>() {
              public AnimalType findValueByNumber(int number) {
                return AnimalType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return MyMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final AnimalType[] VALUES = values();

      public static AnimalType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private AnimalType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.ayy.protobuf.MyMessage.AnimalType)
    }

    private int bitField0_;
    private int oneOfAnimalCase_ = 0;
    private Object oneOfAnimal_;
    public enum OneOfAnimalCase
        implements com.google.protobuf.Internal.EnumLite,
            InternalOneOfEnum {
      CAT(2),
      DOG(3),
      ONEOFANIMAL_NOT_SET(0);
      private final int value;
      private OneOfAnimalCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static OneOfAnimalCase valueOf(int value) {
        return forNumber(value);
      }

      public static OneOfAnimalCase forNumber(int value) {
        switch (value) {
          case 2: return CAT;
          case 3: return DOG;
          case 0: return ONEOFANIMAL_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public OneOfAnimalCase
    getOneOfAnimalCase() {
      return OneOfAnimalCase.forNumber(
          oneOfAnimalCase_);
    }

    public static final int ANIMAL_TYPE_FIELD_NUMBER = 1;
    private int animalType_;
    /**
     * <code>required .com.ayy.protobuf.MyMessage.AnimalType animal_type = 1;</code>
     * @return Whether the animalType field is set.
     */
    @Override public boolean hasAnimalType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .com.ayy.protobuf.MyMessage.AnimalType animal_type = 1;</code>
     * @return The animalType.
     */
    @Override public AnimalType getAnimalType() {
      @SuppressWarnings("deprecation")
      AnimalType result = AnimalType.valueOf(animalType_);
      return result == null ? AnimalType.CAT : result;
    }

    public static final int CAT_FIELD_NUMBER = 2;
    /**
     * <code>.com.ayy.protobuf.Cat cat = 2;</code>
     * @return Whether the cat field is set.
     */
    @Override
    public boolean hasCat() {
      return oneOfAnimalCase_ == 2;
    }
    /**
     * <code>.com.ayy.protobuf.Cat cat = 2;</code>
     * @return The cat.
     */
    @Override
    public Cat getCat() {
      if (oneOfAnimalCase_ == 2) {
         return (Cat) oneOfAnimal_;
      }
      return Cat.getDefaultInstance();
    }
    /**
     * <code>.com.ayy.protobuf.Cat cat = 2;</code>
     */
    @Override
    public CatOrBuilder getCatOrBuilder() {
      if (oneOfAnimalCase_ == 2) {
         return (Cat) oneOfAnimal_;
      }
      return Cat.getDefaultInstance();
    }

    public static final int DOG_FIELD_NUMBER = 3;
    /**
     * <code>.com.ayy.protobuf.Dog dog = 3;</code>
     * @return Whether the dog field is set.
     */
    @Override
    public boolean hasDog() {
      return oneOfAnimalCase_ == 3;
    }
    /**
     * <code>.com.ayy.protobuf.Dog dog = 3;</code>
     * @return The dog.
     */
    @Override
    public Dog getDog() {
      if (oneOfAnimalCase_ == 3) {
         return (Dog) oneOfAnimal_;
      }
      return Dog.getDefaultInstance();
    }
    /**
     * <code>.com.ayy.protobuf.Dog dog = 3;</code>
     */
    @Override
    public DogOrBuilder getDogOrBuilder() {
      if (oneOfAnimalCase_ == 3) {
         return (Dog) oneOfAnimal_;
      }
      return Dog.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAnimalType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, animalType_);
      }
      if (oneOfAnimalCase_ == 2) {
        output.writeMessage(2, (Cat) oneOfAnimal_);
      }
      if (oneOfAnimalCase_ == 3) {
        output.writeMessage(3, (Dog) oneOfAnimal_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, animalType_);
      }
      if (oneOfAnimalCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (Cat) oneOfAnimal_);
      }
      if (oneOfAnimalCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (Dog) oneOfAnimal_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MyMessage)) {
        return super.equals(obj);
      }
      MyMessage other = (MyMessage) obj;

      if (hasAnimalType() != other.hasAnimalType()) return false;
      if (hasAnimalType()) {
        if (animalType_ != other.animalType_) return false;
      }
      if (!getOneOfAnimalCase().equals(other.getOneOfAnimalCase())) return false;
      switch (oneOfAnimalCase_) {
        case 2:
          if (!getCat()
              .equals(other.getCat())) return false;
          break;
        case 3:
          if (!getDog()
              .equals(other.getDog())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAnimalType()) {
        hash = (37 * hash) + ANIMAL_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + animalType_;
      }
      switch (oneOfAnimalCase_) {
        case 2:
          hash = (37 * hash) + CAT_FIELD_NUMBER;
          hash = (53 * hash) + getCat().hashCode();
          break;
        case 3:
          hash = (37 * hash) + DOG_FIELD_NUMBER;
          hash = (53 * hash) + getDog().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MyMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MyMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MyMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ayy.protobuf.MyMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ayy.protobuf.MyMessage)
        MyMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MyDataInfo.internal_static_com_ayy_protobuf_MyMessage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MyDataInfo.internal_static_com_ayy_protobuf_MyMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MyMessage.class, Builder.class);
      }

      // Construct using com.ayy.protobuf.MyDataInfo.MyMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        animalType_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        oneOfAnimalCase_ = 0;
        oneOfAnimal_ = null;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MyDataInfo.internal_static_com_ayy_protobuf_MyMessage_descriptor;
      }

      @Override
      public MyMessage getDefaultInstanceForType() {
        return MyMessage.getDefaultInstance();
      }

      @Override
      public MyMessage build() {
        MyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MyMessage buildPartial() {
        MyMessage result = new MyMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.animalType_ = animalType_;
        if (oneOfAnimalCase_ == 2) {
          if (catBuilder_ == null) {
            result.oneOfAnimal_ = oneOfAnimal_;
          } else {
            result.oneOfAnimal_ = catBuilder_.build();
          }
        }
        if (oneOfAnimalCase_ == 3) {
          if (dogBuilder_ == null) {
            result.oneOfAnimal_ = oneOfAnimal_;
          } else {
            result.oneOfAnimal_ = dogBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.oneOfAnimalCase_ = oneOfAnimalCase_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MyMessage) {
          return mergeFrom((MyMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MyMessage other) {
        if (other == MyMessage.getDefaultInstance()) return this;
        if (other.hasAnimalType()) {
          setAnimalType(other.getAnimalType());
        }
        switch (other.getOneOfAnimalCase()) {
          case CAT: {
            mergeCat(other.getCat());
            break;
          }
          case DOG: {
            mergeDog(other.getDog());
            break;
          }
          case ONEOFANIMAL_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasAnimalType()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MyMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MyMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int oneOfAnimalCase_ = 0;
      private Object oneOfAnimal_;
      public OneOfAnimalCase
          getOneOfAnimalCase() {
        return OneOfAnimalCase.forNumber(
            oneOfAnimalCase_);
      }

      public Builder clearOneOfAnimal() {
        oneOfAnimalCase_ = 0;
        oneOfAnimal_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int animalType_ = 1;
      /**
       * <code>required .com.ayy.protobuf.MyMessage.AnimalType animal_type = 1;</code>
       * @return Whether the animalType field is set.
       */
      @Override public boolean hasAnimalType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .com.ayy.protobuf.MyMessage.AnimalType animal_type = 1;</code>
       * @return The animalType.
       */
      @Override
      public AnimalType getAnimalType() {
        @SuppressWarnings("deprecation")
        AnimalType result = AnimalType.valueOf(animalType_);
        return result == null ? AnimalType.CAT : result;
      }
      /**
       * <code>required .com.ayy.protobuf.MyMessage.AnimalType animal_type = 1;</code>
       * @param value The animalType to set.
       * @return This builder for chaining.
       */
      public Builder setAnimalType(AnimalType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        animalType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .com.ayy.protobuf.MyMessage.AnimalType animal_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAnimalType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        animalType_ = 1;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          Cat, Cat.Builder, CatOrBuilder> catBuilder_;
      /**
       * <code>.com.ayy.protobuf.Cat cat = 2;</code>
       * @return Whether the cat field is set.
       */
      @Override
      public boolean hasCat() {
        return oneOfAnimalCase_ == 2;
      }
      /**
       * <code>.com.ayy.protobuf.Cat cat = 2;</code>
       * @return The cat.
       */
      @Override
      public Cat getCat() {
        if (catBuilder_ == null) {
          if (oneOfAnimalCase_ == 2) {
            return (Cat) oneOfAnimal_;
          }
          return Cat.getDefaultInstance();
        } else {
          if (oneOfAnimalCase_ == 2) {
            return catBuilder_.getMessage();
          }
          return Cat.getDefaultInstance();
        }
      }
      /**
       * <code>.com.ayy.protobuf.Cat cat = 2;</code>
       */
      public Builder setCat(Cat value) {
        if (catBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          oneOfAnimal_ = value;
          onChanged();
        } else {
          catBuilder_.setMessage(value);
        }
        oneOfAnimalCase_ = 2;
        return this;
      }
      /**
       * <code>.com.ayy.protobuf.Cat cat = 2;</code>
       */
      public Builder setCat(
          Cat.Builder builderForValue) {
        if (catBuilder_ == null) {
          oneOfAnimal_ = builderForValue.build();
          onChanged();
        } else {
          catBuilder_.setMessage(builderForValue.build());
        }
        oneOfAnimalCase_ = 2;
        return this;
      }
      /**
       * <code>.com.ayy.protobuf.Cat cat = 2;</code>
       */
      public Builder mergeCat(Cat value) {
        if (catBuilder_ == null) {
          if (oneOfAnimalCase_ == 2 &&
              oneOfAnimal_ != Cat.getDefaultInstance()) {
            oneOfAnimal_ = Cat.newBuilder((Cat) oneOfAnimal_)
                .mergeFrom(value).buildPartial();
          } else {
            oneOfAnimal_ = value;
          }
          onChanged();
        } else {
          if (oneOfAnimalCase_ == 2) {
            catBuilder_.mergeFrom(value);
          }
          catBuilder_.setMessage(value);
        }
        oneOfAnimalCase_ = 2;
        return this;
      }
      /**
       * <code>.com.ayy.protobuf.Cat cat = 2;</code>
       */
      public Builder clearCat() {
        if (catBuilder_ == null) {
          if (oneOfAnimalCase_ == 2) {
            oneOfAnimalCase_ = 0;
            oneOfAnimal_ = null;
            onChanged();
          }
        } else {
          if (oneOfAnimalCase_ == 2) {
            oneOfAnimalCase_ = 0;
            oneOfAnimal_ = null;
          }
          catBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.com.ayy.protobuf.Cat cat = 2;</code>
       */
      public Cat.Builder getCatBuilder() {
        return getCatFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.ayy.protobuf.Cat cat = 2;</code>
       */
      @Override
      public CatOrBuilder getCatOrBuilder() {
        if ((oneOfAnimalCase_ == 2) && (catBuilder_ != null)) {
          return catBuilder_.getMessageOrBuilder();
        } else {
          if (oneOfAnimalCase_ == 2) {
            return (Cat) oneOfAnimal_;
          }
          return Cat.getDefaultInstance();
        }
      }
      /**
       * <code>.com.ayy.protobuf.Cat cat = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Cat, Cat.Builder, CatOrBuilder>
          getCatFieldBuilder() {
        if (catBuilder_ == null) {
          if (!(oneOfAnimalCase_ == 2)) {
            oneOfAnimal_ = Cat.getDefaultInstance();
          }
          catBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Cat, Cat.Builder, CatOrBuilder>(
                  (Cat) oneOfAnimal_,
                  getParentForChildren(),
                  isClean());
          oneOfAnimal_ = null;
        }
        oneOfAnimalCase_ = 2;
        onChanged();;
        return catBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          Dog, Dog.Builder, DogOrBuilder> dogBuilder_;
      /**
       * <code>.com.ayy.protobuf.Dog dog = 3;</code>
       * @return Whether the dog field is set.
       */
      @Override
      public boolean hasDog() {
        return oneOfAnimalCase_ == 3;
      }
      /**
       * <code>.com.ayy.protobuf.Dog dog = 3;</code>
       * @return The dog.
       */
      @Override
      public Dog getDog() {
        if (dogBuilder_ == null) {
          if (oneOfAnimalCase_ == 3) {
            return (Dog) oneOfAnimal_;
          }
          return Dog.getDefaultInstance();
        } else {
          if (oneOfAnimalCase_ == 3) {
            return dogBuilder_.getMessage();
          }
          return Dog.getDefaultInstance();
        }
      }
      /**
       * <code>.com.ayy.protobuf.Dog dog = 3;</code>
       */
      public Builder setDog(Dog value) {
        if (dogBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          oneOfAnimal_ = value;
          onChanged();
        } else {
          dogBuilder_.setMessage(value);
        }
        oneOfAnimalCase_ = 3;
        return this;
      }
      /**
       * <code>.com.ayy.protobuf.Dog dog = 3;</code>
       */
      public Builder setDog(
          Dog.Builder builderForValue) {
        if (dogBuilder_ == null) {
          oneOfAnimal_ = builderForValue.build();
          onChanged();
        } else {
          dogBuilder_.setMessage(builderForValue.build());
        }
        oneOfAnimalCase_ = 3;
        return this;
      }
      /**
       * <code>.com.ayy.protobuf.Dog dog = 3;</code>
       */
      public Builder mergeDog(Dog value) {
        if (dogBuilder_ == null) {
          if (oneOfAnimalCase_ == 3 &&
              oneOfAnimal_ != Dog.getDefaultInstance()) {
            oneOfAnimal_ = Dog.newBuilder((Dog) oneOfAnimal_)
                .mergeFrom(value).buildPartial();
          } else {
            oneOfAnimal_ = value;
          }
          onChanged();
        } else {
          if (oneOfAnimalCase_ == 3) {
            dogBuilder_.mergeFrom(value);
          }
          dogBuilder_.setMessage(value);
        }
        oneOfAnimalCase_ = 3;
        return this;
      }
      /**
       * <code>.com.ayy.protobuf.Dog dog = 3;</code>
       */
      public Builder clearDog() {
        if (dogBuilder_ == null) {
          if (oneOfAnimalCase_ == 3) {
            oneOfAnimalCase_ = 0;
            oneOfAnimal_ = null;
            onChanged();
          }
        } else {
          if (oneOfAnimalCase_ == 3) {
            oneOfAnimalCase_ = 0;
            oneOfAnimal_ = null;
          }
          dogBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.com.ayy.protobuf.Dog dog = 3;</code>
       */
      public Dog.Builder getDogBuilder() {
        return getDogFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.ayy.protobuf.Dog dog = 3;</code>
       */
      @Override
      public DogOrBuilder getDogOrBuilder() {
        if ((oneOfAnimalCase_ == 3) && (dogBuilder_ != null)) {
          return dogBuilder_.getMessageOrBuilder();
        } else {
          if (oneOfAnimalCase_ == 3) {
            return (Dog) oneOfAnimal_;
          }
          return Dog.getDefaultInstance();
        }
      }
      /**
       * <code>.com.ayy.protobuf.Dog dog = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Dog, Dog.Builder, DogOrBuilder>
          getDogFieldBuilder() {
        if (dogBuilder_ == null) {
          if (!(oneOfAnimalCase_ == 3)) {
            oneOfAnimal_ = Dog.getDefaultInstance();
          }
          dogBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Dog, Dog.Builder, DogOrBuilder>(
                  (Dog) oneOfAnimal_,
                  getParentForChildren(),
                  isClean());
          oneOfAnimal_ = null;
        }
        oneOfAnimalCase_ = 3;
        onChanged();;
        return dogBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ayy.protobuf.MyMessage)
    }

    // @@protoc_insertion_point(class_scope:com.ayy.protobuf.MyMessage)
    private static final MyMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MyMessage();
    }

    public static MyMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<MyMessage>
        PARSER = new com.google.protobuf.AbstractParser<MyMessage>() {
      @Override
      public MyMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MyMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MyMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MyMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public MyMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ayy.protobuf.Cat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     * @return The name.
     */
    String getName();
    /**
     * <code>optional string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 age = 2;</code>
     * @return Whether the age field is set.
     */
    boolean hasAge();
    /**
     * <code>optional int32 age = 2;</code>
     * @return The age.
     */
    int getAge();
  }
  /**
   * Protobuf type {@code com.ayy.protobuf.Cat}
   */
  public static final class Cat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ayy.protobuf.Cat)
      CatOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Cat.newBuilder() to construct.
    private Cat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Cat() {
      name_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Cat();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Cat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              age_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MyDataInfo.internal_static_com_ayy_protobuf_Cat_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MyDataInfo.internal_static_com_ayy_protobuf_Cat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Cat.class, Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile Object name_;
    /**
     * <code>optional string name = 1;</code>
     * @return Whether the name field is set.
     */
    @Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string name = 1;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>optional int32 age = 2;</code>
     * @return Whether the age field is set.
     */
    @Override
    public boolean hasAge() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 age = 2;</code>
     * @return The age.
     */
    @Override
    public int getAge() {
      return age_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, age_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Cat)) {
        return super.equals(obj);
      }
      Cat other = (Cat) obj;

      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasAge() != other.hasAge()) return false;
      if (hasAge()) {
        if (getAge()
            != other.getAge()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasAge()) {
        hash = (37 * hash) + AGE_FIELD_NUMBER;
        hash = (53 * hash) + getAge();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Cat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Cat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Cat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Cat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Cat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Cat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Cat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Cat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Cat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Cat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Cat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Cat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Cat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ayy.protobuf.Cat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ayy.protobuf.Cat)
        CatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MyDataInfo.internal_static_com_ayy_protobuf_Cat_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MyDataInfo.internal_static_com_ayy_protobuf_Cat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Cat.class, Builder.class);
      }

      // Construct using com.ayy.protobuf.MyDataInfo.Cat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        age_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MyDataInfo.internal_static_com_ayy_protobuf_Cat_descriptor;
      }

      @Override
      public Cat getDefaultInstanceForType() {
        return Cat.getDefaultInstance();
      }

      @Override
      public Cat build() {
        Cat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Cat buildPartial() {
        Cat result = new Cat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.age_ = age_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Cat) {
          return mergeFrom((Cat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Cat other) {
        if (other == Cat.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Cat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Cat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string name = 1;</code>
       * @return The name.
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>optional int32 age = 2;</code>
       * @return Whether the age field is set.
       */
      @Override
      public boolean hasAge() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 age = 2;</code>
       * @return The age.
       */
      @Override
      public int getAge() {
        return age_;
      }
      /**
       * <code>optional int32 age = 2;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        bitField0_ |= 0x00000002;
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 age = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000002);
        age_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ayy.protobuf.Cat)
    }

    // @@protoc_insertion_point(class_scope:com.ayy.protobuf.Cat)
    private static final Cat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Cat();
    }

    public static Cat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Cat>
        PARSER = new com.google.protobuf.AbstractParser<Cat>() {
      @Override
      public Cat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Cat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Cat> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Cat> getParserForType() {
      return PARSER;
    }

    @Override
    public Cat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DogOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ayy.protobuf.Dog)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     * @return The name.
     */
    String getName();
    /**
     * <code>optional string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 age = 2;</code>
     * @return Whether the age field is set.
     */
    boolean hasAge();
    /**
     * <code>optional int32 age = 2;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <code>optional string race = 3;</code>
     * @return Whether the race field is set.
     */
    boolean hasRace();
    /**
     * <code>optional string race = 3;</code>
     * @return The race.
     */
    String getRace();
    /**
     * <code>optional string race = 3;</code>
     * @return The bytes for race.
     */
    com.google.protobuf.ByteString
        getRaceBytes();
  }
  /**
   * Protobuf type {@code com.ayy.protobuf.Dog}
   */
  public static final class Dog extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ayy.protobuf.Dog)
      DogOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Dog.newBuilder() to construct.
    private Dog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Dog() {
      name_ = "";
      race_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Dog();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Dog(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              age_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              race_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MyDataInfo.internal_static_com_ayy_protobuf_Dog_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MyDataInfo.internal_static_com_ayy_protobuf_Dog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Dog.class, Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile Object name_;
    /**
     * <code>optional string name = 1;</code>
     * @return Whether the name field is set.
     */
    @Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string name = 1;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>optional int32 age = 2;</code>
     * @return Whether the age field is set.
     */
    @Override
    public boolean hasAge() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 age = 2;</code>
     * @return The age.
     */
    @Override
    public int getAge() {
      return age_;
    }

    public static final int RACE_FIELD_NUMBER = 3;
    private volatile Object race_;
    /**
     * <code>optional string race = 3;</code>
     * @return Whether the race field is set.
     */
    @Override
    public boolean hasRace() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string race = 3;</code>
     * @return The race.
     */
    @Override
    public String getRace() {
      Object ref = race_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          race_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string race = 3;</code>
     * @return The bytes for race.
     */
    @Override
    public com.google.protobuf.ByteString
        getRaceBytes() {
      Object ref = race_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        race_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, age_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, race_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, race_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Dog)) {
        return super.equals(obj);
      }
      Dog other = (Dog) obj;

      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasAge() != other.hasAge()) return false;
      if (hasAge()) {
        if (getAge()
            != other.getAge()) return false;
      }
      if (hasRace() != other.hasRace()) return false;
      if (hasRace()) {
        if (!getRace()
            .equals(other.getRace())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasAge()) {
        hash = (37 * hash) + AGE_FIELD_NUMBER;
        hash = (53 * hash) + getAge();
      }
      if (hasRace()) {
        hash = (37 * hash) + RACE_FIELD_NUMBER;
        hash = (53 * hash) + getRace().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Dog parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Dog parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Dog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Dog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Dog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Dog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Dog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Dog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Dog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Dog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Dog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Dog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Dog prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ayy.protobuf.Dog}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ayy.protobuf.Dog)
        DogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MyDataInfo.internal_static_com_ayy_protobuf_Dog_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MyDataInfo.internal_static_com_ayy_protobuf_Dog_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Dog.class, Builder.class);
      }

      // Construct using com.ayy.protobuf.MyDataInfo.Dog.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        age_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        race_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MyDataInfo.internal_static_com_ayy_protobuf_Dog_descriptor;
      }

      @Override
      public Dog getDefaultInstanceForType() {
        return Dog.getDefaultInstance();
      }

      @Override
      public Dog build() {
        Dog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Dog buildPartial() {
        Dog result = new Dog(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.age_ = age_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.race_ = race_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Dog) {
          return mergeFrom((Dog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Dog other) {
        if (other == Dog.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        if (other.hasRace()) {
          bitField0_ |= 0x00000004;
          race_ = other.race_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Dog parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Dog) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string name = 1;</code>
       * @return The name.
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>optional int32 age = 2;</code>
       * @return Whether the age field is set.
       */
      @Override
      public boolean hasAge() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 age = 2;</code>
       * @return The age.
       */
      @Override
      public int getAge() {
        return age_;
      }
      /**
       * <code>optional int32 age = 2;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        bitField0_ |= 0x00000002;
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 age = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000002);
        age_ = 0;
        onChanged();
        return this;
      }

      private Object race_ = "";
      /**
       * <code>optional string race = 3;</code>
       * @return Whether the race field is set.
       */
      public boolean hasRace() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string race = 3;</code>
       * @return The race.
       */
      public String getRace() {
        Object ref = race_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            race_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string race = 3;</code>
       * @return The bytes for race.
       */
      public com.google.protobuf.ByteString
          getRaceBytes() {
        Object ref = race_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          race_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string race = 3;</code>
       * @param value The race to set.
       * @return This builder for chaining.
       */
      public Builder setRace(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        race_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string race = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRace() {
        bitField0_ = (bitField0_ & ~0x00000004);
        race_ = getDefaultInstance().getRace();
        onChanged();
        return this;
      }
      /**
       * <code>optional string race = 3;</code>
       * @param value The bytes for race to set.
       * @return This builder for chaining.
       */
      public Builder setRaceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        race_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ayy.protobuf.Dog)
    }

    // @@protoc_insertion_point(class_scope:com.ayy.protobuf.Dog)
    private static final Dog DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Dog();
    }

    public static Dog getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Dog>
        PARSER = new com.google.protobuf.AbstractParser<Dog>() {
      @Override
      public Dog parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Dog(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Dog> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Dog> getParserForType() {
      return PARSER;
    }

    @Override
    public Dog getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ayy_protobuf_MyMessage_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ayy_protobuf_MyMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ayy_protobuf_Cat_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ayy_protobuf_Cat_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ayy_protobuf_Dog_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ayy_protobuf_Dog_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014Animal.proto\022\020com.ayy.protobuf\"\303\001\n\tMyM" +
      "essage\022;\n\013animal_type\030\001 \002(\0162&.com.ayy.pr" +
      "otobuf.MyMessage.AnimalType\022$\n\003cat\030\002 \001(\013" +
      "2\025.com.ayy.protobuf.CatH\000\022$\n\003dog\030\003 \001(\0132\025" +
      ".com.ayy.protobuf.DogH\000\"\036\n\nAnimalType\022\007\n" +
      "\003CAT\020\001\022\007\n\003DOG\020\002B\r\n\013oneOfAnimal\" \n\003Cat\022\014\n" +
      "\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\".\n\003Dog\022\014\n\004name\030" +
      "\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\014\n\004race\030\003 \001(\tB \n\020com." +
      "ayy.protobufB\nMyDataInfoH\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_ayy_protobuf_MyMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ayy_protobuf_MyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ayy_protobuf_MyMessage_descriptor,
        new String[] { "AnimalType", "Cat", "Dog", "OneOfAnimal", });
    internal_static_com_ayy_protobuf_Cat_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ayy_protobuf_Cat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ayy_protobuf_Cat_descriptor,
        new String[] { "Name", "Age", });
    internal_static_com_ayy_protobuf_Dog_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_ayy_protobuf_Dog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ayy_protobuf_Dog_descriptor,
        new String[] { "Name", "Age", "Race", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
