server:
  port: 10004

mybatis:
  type-aliases-package: com.ayy.springcloud.bean
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-4xo63l909kdrexz8kio.mysql.germany.rds.aliyuncs.com:3306/cloudapi
    username: cloud
    password: SPRINGcloud01

eureka:
  instance:
    instance-id: springcloud-provider-eureka-dept-10004
  client:
    service-url:
      defaultZone: http://eureka1:10003/eureka/,http://eureka2:10005/eureka/,http://eureka3:10006/eureka/

info:
  app.name: ayy-springcloud
  company.name: com.ayy
