// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.ayy.grpc;

public interface MyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ayy.grpc.MyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string studentname = 1;</code>
   * @return The studentname.
   */
  String getStudentname();
  /**
   * <code>string studentname = 1;</code>
   * @return The bytes for studentname.
   */
  com.google.protobuf.ByteString
      getStudentnameBytes();
}
